#' @title Predict Sonar Statistics based on Percentiles
#' @description A method for anticipating sonar total count and species composition
#'   variables to use in harvest prediction.
#' @param date datetime object storing the date of the opener to be predicted.
#' @param lag number of days before the proposed opener the prediction is to be made.
#' @param fit_data [`data.frame`][base::data.frame] storing the variables for regression fitting; generated by [KuskoHarvData::prepare_regression_data()]
#' @details This prediction method works by assuming the percentile of the sonar statistic on the day of the opener
#'   relative to all historical years (since 2018) will be the same as it is on the day of prediction.
#'   E.g., for a proposed June 12 opener with a 5 day lag: if on June 7 it is determined that 25% of all historical sonar stats fell below
#'   this year's stat, then the prediction for June 12 is obtained as the value that 25% of all historical sonar stats
#'   fell below on June 12.
#'
#'   This approach was developed in response to peer review feedback, given a concern that our original LOO analysis under-represented
#'   errors in prediction because we originally evaluated them at the actual BTF statistics (which would be unavailable to users of the model -- manuscript version used BTF values rather than sonar).
#'   By using this approach instead, the intention is to use a more realistic version of what will actually be available to users of the
#'   tool for evaluation of predictive performance.
#'   The notion extends to the use of sonar in current and future versions of the analysis.
#' @note This function may only be used if `date` is contained within the data set `sonar_data_all` in the `KuskoHarvData` package.
#' @return A [`data.frame`][base::data.frame] object with a single row, and columns for
#'   `date`, `total_sonar_count`, `chinook_sonar_comp`, `chum_sonar_comp`, and `sockeye_sonar_comp`, the latter 4 contain the predicted values.

predict_sonar = function(date, lag) {

  # convert the input date to datetime if not already there
  date = lubridate::as_date(date)
  year = lubridate::year(date)

  # get the date the prediction is made (date of proposed fishery minus lag)
  pred_date = date - lag

  # load sonar data, and store the years that will be used to build the historical percentiles
  data(sonar_data_all, package = "KuskoHarvData")
  hist_yrs = unique(lubridate::year(sonar_data_all$date))
  hist_yrs = hist_yrs[-which(hist_yrs == year)]

  # get the dates from which the historical predictive percentiles will be based
  hist_dates = rep(pred_date, length(hist_yrs))
  lubridate::year(hist_dates) = hist_yrs

  # get the dates from which the historical percentiles on the day of the opener will be based
  dates = rep(date, length(hist_yrs))
  lubridate::year(dates) = hist_yrs

  # function to obtain sonar stats for a given date
  summarize_sonar2 = function(d) {
    out = data.frame(
      date = d,
      chinook = KuskoHarvData:::summarize_sonar(d, "chinook_count", plus_minus = 0),
      chum = KuskoHarvData:::summarize_sonar(d, "chum_count", plus_minus = 0),
      sockeye = KuskoHarvData:::summarize_sonar(d, "sockeye_count", plus_minus = 0)
    )
    out$total = out$chinook + out$chum + out$sockeye
    out$p_chinook = out$chinook/out$total
    out$p_chum = out$chum/out$total
    out$p_sockeye = out$sockeye/out$total
    return(out)
  }

  # get sonar stats for all historical years on the date of the prediction
  hist_counts = do.call(rbind, lapply(hist_dates, summarize_sonar2))

  # get sonar stats for this year on the date of the prediction
  obs_counts = summarize_sonar2(pred_date)

  # using the empirical CDF, obtain the percentile of historical values that this year's value falls at
  # perform separately for each stat
  obs_perc_total = ecdf(hist_counts$total)(obs_counts$total)
  obs_perc_p_chinook = ecdf(hist_counts$p_chinook)(obs_counts$p_chinook)
  obs_perc_p_chum = ecdf(hist_counts$p_chum)(obs_counts$p_chum)
  obs_perc_p_sockeye = ecdf(hist_counts$p_sockeye)(obs_counts$p_sockeye)

  # get sonar stats for all historical years on the date of the proposed fishery
  counts = do.call(rbind, lapply(dates, summarize_sonar2))

  # obtain value associated with the same percentile observed thus far in season, but for the date of the proposed fishery
  pred_cpue_total = unname(quantile(counts$total, obs_perc_total))
  pred_p_chinook = unname(quantile(counts$p_chinook, obs_perc_p_chinook))
  pred_p_chum = unname(quantile(counts$p_chum, obs_perc_p_chum))
  pred_p_sockeye = unname(quantile(counts$p_sockeye, obs_perc_p_sockeye))

  # sum the species compositions, for normalizing to sum to 1
  pred_p_sum = pred_p_chinook + pred_p_chum + pred_p_sockeye

  # build the output
  data.frame(date = date,
             total_sonar_count = pred_cpue_total,
             chinook_sonar_comp = pred_p_chinook/pred_p_sum,
             chum_sonar_comp = pred_p_chum/pred_p_sum,
             sockeye_sonar_comp = pred_p_sockeye/pred_p_sum

  )
}

#' @title Obtain Leave-one-Out Predictions from a Single Model
#' @param fit A fitted model object of class [`lm`][stats::lm].
#' @param lag number of days before the proposed opener the prediction is to be made. See [predict_sonar()].
#'   Ignored if model does not contain a sonar variable.
#' @param fit_data [`data.frame`][base::data.frame] storing the variables for regression fitting; generated by [KuskoHarvData::prepare_regression_data()]
#' @return A [`matrix`][base::matrix] object with columns storing values for each record and rows storing the predicted value for
#'   the left out observation and the AICc value (given by [MuMIn::AICc()]) of the model fitted after leaving the data point out.

loo_pred = function(fit, lag, fit_data) {

  # loop through observations leaving one out at a time
  # fit model to training data, predict value of test data
  sapply(1:nrow(fit$model), function(i) {
    # build training data set (with one observation left out)
    train_dat = as.data.frame(fit$model[-i,]); colnames(train_dat) = colnames(fit$model)

    # build the test data set (with only the left out observation)
    test_dat = as.data.frame(fit$model[i,]); colnames(test_dat) = colnames(fit$model)

    # if any sonar stats are included in data set for this model
    # predict them at specified lag (i.e., days before fishery)
    # and replace actual sonar stat value with predicted value
    # more realistic than using actual sonar stat, because this is unknown at time of prediction
    if (any(stringr::str_detect(colnames(test_dat), "sonar"))) {
      sonar_preds = predict_sonar(date = fit_data$date[i], lag = lag)
      if ("total_sonar_count" %in% colnames(test_dat)) test_dat[,"total_sonar_count"] = sonar_preds["total_sonar_count"]
      if ("chinook_sonar_comp" %in% colnames(test_dat)) test_dat[,"chinook_sonar_comp"] = sonar_preds["chinook_sonar_comp"]
      if ("I(chinook_sonar_comp^2)" %in% colnames(test_dat)) test_dat[,"I(chinook_sonar_comp^2)"] = sonar_preds["chinook_sonar_comp"]^2
      if ("chum_sonar_comp" %in% colnames(test_dat)) test_dat[,"chum_sonar_comp"] = sonar_preds["chum_sonar_comp"]
      if ("I(chum_sonar_comp^2)" %in% colnames(test_dat)) test_dat[,"I(chum_sonar_comp^2)"] = sonar_preds["chum_sonar_comp"]^2
      if ("sockeye_sonar_comp" %in% colnames(test_dat)) test_dat[,"sockeye_sonar_comp"] = sonar_preds["sockeye_sonar_comp"]
      if ("I(sockeye_sonar_comp^2)" %in% colnames(test_dat)) test_dat[,"I(sockeye_sonar_comp^2)"] = sonar_preds["sockeye_sonar_comp"]^2
    }

    # fit the model to training data set
    loo_fit = lm(formula(fit), data = train_dat)

    # use this model to predict the response value of the test data set
    loo_pred = unname(inverse_transform(fit)(predict(loo_fit, newdata = test_dat)))

    # return the prediction and AICc for this left out sample
    c(loo_pred = loo_pred,
      AICc = MuMIn::AICc(loo_fit)
    )
  })
}

#' @title Obtain Model-Averaged Leave-one-Out Predictions
#' @inheritParams predict_model_avg
#' @param lag number of days before the proposed opener the prediction is to be made. See [predict_sonar()].
#' @return Numeric vector of model-averaged leave-one-out predictions.
#' @note Leave-one-out predictions are made for each model and each record
#'   using [loo_pred()] and model weights are recalculated for each left out record
#'   prior to averaging the predictions from each model.
#' @export

loo_pred_model_avg = function(fit_list, lag, fit_data) {

  # make loo predictions and calculate AICc for each loo for each model
  loo = lapply(fit_list, loo_pred, lag = lag, fit_data = fit_data)

  # extract/format the loo predictions
  loo_preds = do.call(cbind, lapply(loo, function(x) x["loo_pred",]))

  # extract/format the loo predictions
  loo_AICcs = do.call(cbind, lapply(loo, function(x) x["AICc",]))

  # calculate AICc weight for each loo
  loo_wts = t(apply(loo_AICcs, 1, get_wt))

  # calculate model-averaged loo prediction
  loo_pred_model_avg = sapply(1:nrow(loo_preds), function(i) sum(loo_preds[i,] * loo_wts[i,]))

  # return
  return(loo_pred_model_avg)
}

#' @title Conduct the Entire Leave-one-Out Analysis
#' @description A wrapper around model-fitting, model-averaging, leave-one-out calculations, and error summaries
#'   for effort, catch rate, and species composition; also returns predictions and error summaries of harvest implied by the values of the other variables.
#' @inheritParams fit_all_subsets
#' @param var_desc Optional character string describing the variables used in fitting.
#'   If supplied, will become the first column in the `error_summary` element of the output list.
#' @param error_types A character vector specifying which types of error summaries (obtained by [KuskoHarvUtils::get_errors()]) to return.
#'   Options are any combination of `"RHO"`, `"RMSE"`, `"ME"`, `"MAE"`, `"MPE"`, or `"MAPE"`.
#' @param lag number of days before the proposed opener the prediction is to be made. See [predict_sonar()].
#' @param ... Optional arguments passed to [fit_all_subsets()]
#' @details This function conducts several steps in a self-contained wrapper:
#'   1. Fits the global models to each response variable using [fit_global_model_one()].
#'   2. Fits all subsets of these global models using [fit_all_subsets()].
#'   3. Obtains model-averaged leave-one-out predictions for each record using [loo_pred_model_avg()].
#'   4. Summarizes the errors made in step 3 by response variable type and period (see [KuskoHarvUtils::get_errors()] and [KuskoHarvUtils::get_period()]).
#' @return [`list`][base::list] with elements:
#'   * `error_summary`: [`list`][base::list] with elements storing [`data.frame`][base::data.frame] objects, where each data frame stores info about the settings of the run (the values of `reduce_colinearity`, `cwt_retain`, and `var_desc`) and the period- and response variable-specific error summaries. Different list elements store the different error summary statistics supplied to `error_types`.
#'   * `elapsed`: [`data.frame`][base::data.frame] similar to the `error_summary` element, except with a column for minutes elapsed.
#'   * `loo_preds`: [`data.frame`][base::data.frame] with the model-averaged leave-one-out predictions by record and response variable.
#'   * `models`: a [`list`][base::list] with 5 elements, one each for `effort`, `total_cpt`, and `chinook_comp`, `chum_comp`, and `sockeye_comp`. Each element is the [`list`][base::list] of fitted [`lm`][stats::lm] model objects returned by [fit_all_subsets()].
#' @export

whole_loo_analysis = function(global_formulae, fit_data, var_desc = NULL, error_types = c("RHO", "ME", "MAE", "MPE", "MAPE"), lag, ...) {

  # start a timer
  start = lubridate::now()

  # STEP 1: fit all models and select the top according to the settings
  model_lists = fit_all_subsets(global_formulae = global_formulae, fit_data = fit_data, ...)

  # STEP 2: obtain model-averaged leave-one-out predictions for each response variable
  loo_preds = lapply(model_lists, loo_pred_model_avg, lag = lag, fit_data = fit_data)

  # STEP 3: rescale composition variables so they sum to 1
  chinook_comp_new = with(loo_preds, chinook_comp/(chinook_comp + chum_comp + sockeye_comp))
  chum_comp_new = with(loo_preds, chum_comp/(chinook_comp + chum_comp + sockeye_comp))
  sockeye_comp_new = with(loo_preds, sockeye_comp/(chinook_comp + chum_comp + sockeye_comp))
  loo_preds$chinook_comp = chinook_comp_new
  loo_preds$chum_comp = chum_comp_new
  loo_preds$sockeye_comp = sockeye_comp_new

  # STEP 4: obtain model-averaged leave-one-out harvest predictions for all species that had composition models fitted
  spp = c("chinook", "chum", "sockeye")
  harv_loo_preds = lapply(spp, function(x) {
    spp_comp = paste0(x, "_comp")
    loo_preds$effort * loo_preds$total_cpt * loo_preds[[spp_comp]]
  })
  names(harv_loo_preds) = paste0(spp, "_harv")
  loo_preds = append(loo_preds, harv_loo_preds)
  # MAIN = loo_preds

  # STEP 5: summarize the errors
  summarize_errors = function(yhat, response, fit_data, error_types) {
      # build a data.frame with time period, prediction, and observed values
      df = data.frame(period = KuskoHarvUtils::get_period(fit_data$day), yhat = yhat, yobs = fit_data[,response])

      # calculate MPE and MAPE for each period separately
      errors = lapply(unique(df$period), function(p) {
        KuskoHarvUtils::get_errors(yhat = df$yhat[df$period == p], yobs = df$yobs[df$period == p])$summary[error_types]
      })

      # calculate MPE and MAPE for all periods combined, and append to period-specific values
      errors = append(
        errors,
        list(KuskoHarvUtils::get_errors(yhat = df$yhat, yobs = df$yobs)$summary[error_types])
      )

      # convert errors to a data frame: periods as rows
      errors = as.data.frame(do.call(rbind, errors))

      # combine with other info
      cbind(period = c(1,2,3,"all"), response = response, errors)
    }

  error_summary = lapply(names(loo_preds), function(resp) summarize_errors(loo_preds[[resp]], resp, fit_data = fit_data, error_types = error_types))
  error_summary = do.call(rbind, error_summary)

  # add a n_models variable
  n_models = lapply(model_lists, length)
  n_models = data.frame(response = names(n_models), n_models = unname(unlist(n_models)))
  error_summary = merge(error_summary, n_models, by = "response", all = TRUE)

  # make long format
  x = reshape2::melt(error_summary, id.vars = c("period", "response", "n_models"), variable.name = "type", value.name = "value")

  # make wide format
  x = reshape2::dcast(x, response + n_models ~ type + period, value.var = "value")

  # combine with other meta-information about the analysis
  error_summary = cbind(
    reduce_colinearity = ifelse(attr(model_lists[[1]], "subset_params")$reduce_colinearity, "Yes", "No"),
    cwt_retain = attr(model_lists[[1]], "subset_params")$cwt_retain,
    x
  )
  if (!is.null(var_desc)) {
    error_summary = cbind(var_desc = var_desc, error_summary)
  }

  # reorder rows
  error_summary$response = as.character(error_summary$response)
  rownames(error_summary) = error_summary$response
  error_summary = error_summary[c("effort", "total_cpt", "chinook_comp", "chum_comp", "sockeye_comp", "chinook_harv", "chum_harv", "sockeye_harv"),]
  rownames(error_summary) = NULL

  # split up error summaries
  error_summary = lapply(error_types, function(x) {
    id_vars = colnames(error_summary)[!stringr::str_detect(colnames(error_summary), paste(error_types, collapse = "|"))]
    error_summary[,c(id_vars, colnames(error_summary)[stringr::str_detect(colnames(error_summary), x)])]
  }); names(error_summary) = error_types

  # stop the timer
  stop = lubridate::now()

  # calculate elapsed time and format as data frame
  elapsed = data.frame(
    mins_elapsed = lubridate::int_length(lubridate::int_diff(c(start, stop)))/60
  )
  elapsed = cbind(
    reduce_colinearity = ifelse(attr(model_lists[[1]], "subset_params")$reduce_colinearity, "Yes", "No"),
    cwt_retain = attr(model_lists[[1]], "subset_params")$cwt_retain,
    elapsed
  )
  if (!is.null(var_desc)) {
    elapsed = cbind(var_desc = var_desc, elapsed)
  }

  # build the list object to return
  output = list(
    error_summary = error_summary,
    elapsed = elapsed,
    loo_preds = as.data.frame(do.call(cbind, loo_preds)),
    models = model_lists
  )

  # return the output
  return(output)
}
